apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-elibrary-deployment
  labels:
    app: e-library-v4
spec:
  replicas: 2
  selector:
    matchLabels:
      app: e-library-v4
  template:
    metadata:
      labels:
        app: e-library-v4
    spec:
      containers:
      - name: e-library-v5-latest
        image: apjg7/e_library_v4:b8a01a122de85987ef841c570ca32b69d2704d6e
        ports:
        - containerPort: 8000
        volumeMounts:
          - name: volume-v1
            mountPath: /opt
      volumes:
        - name: volume-v1
          configMap:
            name: test-config
