apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-blog-deployment
  namespace: default
  labels:
    app: blog-v4
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blog-v4
  template:
    metadata:
      labels:
        app: blog-v4
    spec:
      containers:
      - name: blog-latest
        image: apjg7/blog_v4:add7327d4d319625072c180c95a80292f926a03a
        ports:
        - containerPort: 8000
