apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-blog-deployment
  namespace: default
  labels:
    app: blog-v4
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blog-v4
  template:
    metadata:
      labels:
        app: blog-v4
    spec:
      containers:
      - name: blog-latest
        image: apjg7/blog_v4:853c34da2ffb595bcde220496b9d38ed8f654f56
        ports:
        - containerPort: 8000
        volumeMounts:
          - name: volume-v1
            mountPath: /opt
      volumes:
        - name: volume-v1
          configMap:
            name: test-config
