apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-elibrary-deployment
  labels:
    app: e-library-v4
spec:
  replicas: 2
  selector:
    matchLabels:
      app: e-library-v4
  template:
    metadata:
      labels:
        app: e-library-v4
    spec:
      containers:
      - name: e-library-v5-latest
        image: apjg7/e_library_v4:5b1dc5430df9897200b97ad1747ed2cc40c51162
        ports:
        - containerPort: 8000
        volumeMounts:
          - name: volume-v1
            mountPath: /opt
      volumes:
        - name: volume-v1
          configMap:
            name: test-config
