apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-blog-deployment
  namespace: default # Specify your namespace here
  labels:
    app: blog-v4
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blog-v4
  template:
    metadata:
      labels:
        app: blog-v4
    spec:
      containers:
      - name: blog-latest
        image: apjg7/blog_v4:8c086b75610209de10a1a37e3682c16a57e316f4
        ports:
        - containerPort: 8000
        volumeMounts:
          - name: volume-v1
            mountPath: /opt
      volumes:
        - name: volume-v1
          configMap:
            name: test-config
