name: Blog_Django

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Django System Check
      - name: Django System Check
        run: python manage.py check

      # Step 5: Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 6: Build and Push Docker Image
      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME=apjg7/blog_v4:${{ github.sha }}
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME
          echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV

      # Step 7: Update Deployment YAML
      - name: Update image for Django container in deployment.yml
        uses: loveholidays/gitops-action-yaml-updater@v1.0
        with:
          mode: IMAGE_TAG
          container-name: blog-latest
          new-image-tag: ${{ env.IMAGE_TAG }}
          filepath: deployment.yml

      # Step 8: Verify Updated Deployment YAML
      - name: Verify Updated Deployment YAML
        run: cat deployment.yml

      # Step 9: Commit and Push Changes
      - name: Commit and Push Changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: APJG-7
          author_email: apj752003@gmail.com
          message: 'Updated deployment'
          add: 'deployment.yml'

      # Step 10: Verify Latest Commit
      - name: Verify Latest Commit
        run: |
          git fetch origin main
          git log -1 --oneline
