name: Blog_Django

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Django System Check
      - name: Django System Check
        run: python manage.py check
        
      - name: Run Tests with Coverage
        run: |
          pip install coverage
          coverage run --source='.' manage.py test
          coverage xml -o coverage.xml

      # Step 5: Upload Coverage to Codacy
      - name: Codacy Coverage Report
        run: |
          curl -Ls https://coverage.codacy.com/get.sh > codacy-coverage-reporter.sh
          chmod +x codacy-coverage-reporter.sh
          ./codacy-coverage-reporter.sh report \
            --project-token ${{ secrets.CODACY_PROJECT_TOKEN }} \
            -r coverage.xml
      # Step 6: Initialize CodeQL
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: 'python'
  
      - name: Autobuild
        uses: github/codeql-action/autobuild@v1
  
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1

      # Step 7: Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 8: Build and Push Docker Image
      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME=apjg7/blog_v4:${{ github.sha }}
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME
          echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV

      # Step 9: Update Deployment YAML
      - name: Update image for Django container in deployment.yml
        uses: loveholidays/gitops-action-yaml-updater@v1.0
        with:
          mode: IMAGE_TAG
          container-name: blog-latest
          new-image-tag: ${{ env.IMAGE_TAG }}
          filepath: deployment.yml

      # Step 10: Verify Updated Deployment YAML
      - name: Verify Updated Deployment YAML
        run: cat deployment.yml

      # Step 11: Commit and Push Changes
      - name: Commit and Push Changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: APJG-7
          author_email: apj752003@gmail.com
          message: 'Updated deployment'
          add: 'deployment.yml'

      # Step 12: Verify Latest Commit
      - name: Verify Latest Commit
        run: |
          git fetch origin main
          git log -1 --oneline
