name: E-library-Django

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  E-library:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Django System Check
        run: python manage.py check

      - name: Test Linting
        run: pip install flake8 && flake8 .
