name: E-library-Django

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  E-library:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Django System Check
        run: python manage.py check
        
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME=apjg7/e-library-${{ github.sha }}
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME
          
      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME=apjg7/e_library_v4:${{ github.sha }}
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

      # Step 3: Update Deployment YAML
      - name: Update Deployment YAML with Latest Image
        run: |
          sed -i "s|PLACEHOLDER_IMAGE|$IMAGE_NAME|g" deployment.yml
